language: python
python: 3.5
install:
  - pip install flake8
  - pip install -e .
script:
  - flake8
deploy:
  provider: pypi
  user: "fahlberg"
  password:
    secure: "SlBNe+L2GdNGK9597vhx+zxRHmsg9TKUmPKxP6W06QBz9SJsCK7pwXlXeRZcqV6KeMfi/ZMZVuHomSXOl7hnq1v/xvCRmpMXNMMIvFN2m2LgqUvMFbFJVGxlXNZlWHiliPdg6X+XQxAhAeYQDTsWKr6ORoaQZLiUbyoXuf5c+vltm8TsNhPSkljuwU2SMVCC/Se47Mao75NgEfXVdvwdtA4cD6Uabwx3QBghhhG0aNKl+7Q5jxLKN2FKP7NvD3mnFc2wTtxYgStdm0WKWY0jpQ/LXDJKmjlN7mlkXyW1eY5VhxNm+IPZ19s8jXHFRxd92tdTUVE0GdplX70KckFwkFQOVnHmA5pvXNmPjvoO14GzUwtO7AzZW713/1AJ4nrDyJ5+zNjXVWVbm1yg0IYbo+K0uDZO6d2JS0LB6wtDWIu0tXD8zwdWLkF8S+YTq8iGHf9atqM4s4Yn/3cscVvB4eyhw7HOYh71hK7o5qXrhx8+J9sQ8km1l5iAWk6N8BMH+H3kPqBirpSe3JbXAGA9war55T1pnI5Fe5i+ACulQCfs3O/vhHIlDfpV8f+47YYSdY8x8YtoMHpAa4etn1Dr/rnwpgxa9BnACPt3oLrsdBp7ZgKIijIUUTownkB0i5XMx6ULmsXem8nDRNfYDb1g+cRGdy3FO+WlZWN8zb670e4="
  on:
    tags: true