language: python
python: 3.5
install:
- pip install flake8
- pip install -e .
script:
- flake8
deploy:
  provider: pypi
  user: fahlberg
  password:
    secure: g2mUTele7PGH6kXXMi1O+vWZxO9wwXV+ZiKE1R0KEm9ZK2hsymNfLx8le3gQ/Esg9knZj8YKUzwJdyVxrhMdYwUHOg9jOWppURNKD1eoWce+hrvoNGrdjyPS0BJOuG6KYbLZUt612EJfA+zO50e05Ou+nUolpn04S4bl6V0fGQZY3VA6mYyVcjkCcBcWEmosyx2X25ySCBssqz3lAzbYawHInn9slXTOtoyl2kO7xCaWtDcgBlj6ptJz5wfpX/4UkaYJAD4u3XmM37vw+ptwvBGu6XxtBfr1btAkeESCYJVw/+K05em5dj+4iXG5EmJW8rTEpZ1yBsbbuKg+Cryo/R3NmQNX93UoydNGDNLbCZ/Cx4aCigKm3OTGrgOnFSmGGKv3shq3DNYIbtiSZrcXdjETtiihwbROEFx5ar9YmZImOdxKISuqSbGKyfCWG2LAng8/e5+EDtdW36FAZSahgLXCiNXGPF7aWXrERog1rXz0vv5+0q2xRaI92oDQQJLmBj+J6So12LaqdfZ6of3svgtJfoXD1eIP6tcuZVh2yHmqBGC8ayhGs/M9bDsxTtifgN/f8QFLLPGkv54IxYRlq7uATHT2vOOuitRXSStsk2+kPXJnW4wxYOGD4DH64PNOsnczsWnmclJ12gcHFd+wbnlQeh0WUqF27YChOREOufE=
  on:
    tags: true
