language: python
python: 3.5
install:
- pip install flake8
- pip install -e .
script:
- flake8
deploy:
  provider: pypi
  user: fahlberg
  password:
    secure: Bzr3Q0XhZWJqulPJBgnHfmUHl0wltzuR1QIiCRIIHJ728LrnCV1l6i7Xs361WrXFkZhvloNIcfL8iIs6nrBOCkXOYB0ne0tIu1nl+MuH3a6EqcZ/yKkfSf31ela1Zjp5mTm2GJ9vq57yIyuS6pwp1bvkFq5K5ANDdjR4QzkdkUbe0QvghTUTESEi+zDgYTaLu9Qrizk3WNDdP9pByKc73TOecPznZY7byrZx6FOI+ZR7g1b/SB3rxOl/jOFHQXa5Gen55V5uC+dVMVvVAyksxV9777iFBV4zMkCZYYw8q3veECoO5NEkcrBQN1myJ26tX+NDfP+aK2A4QYaHky8dTL2y86X8LQgx5UmQCf8LCA5l3fp0PI9iTboYu7FJ0K19GkNkYHpdS4KqEYgvGdMa9szpgyrj9K4Z2QvbMEeaP2186vfUNJnXYKQ0BGkJ9ThkAzU2DUyY7gNWaeXIXPvSNyIueox1TJxDbnp+/KsUgxdEon6xL34b6DI7+9ly57AxIkjXBQfJ4X/ge3aWAsFqMXHoYidtzGi7Chf3uysCrsR4SxmRyDL7qwEkFhzu1gJGJDVeBr/jkn/QGse6XVhmNpmoUY+q4b+x+7DM731Y5cfvquggnbI3ndBJ0vM2HzHSnWz665+nkhgtGcPnqXf4xY2/KC98doXvzeBz92XZMpU=
  on:
    tags: true
