language: python
python: 3.5
install:
  - pip install flake8
  - pip install -e .
script:
  - flake8
deploy:
  provider: pypi
  user: fahlberg
  password:
    secure: "Khr9SnFKdTPqJMCaDKou5NeVkW+DWdl0zFJi8o8tP2EvvoLjtEuXl4HosH/+JpBCbARq/tZOrWZPJQN0pWxA60otUIYd+6W5HO9mb3L9rIbscWvjwzRbr4jCPBHbqXOEzrUbuoUz4L+V0VSWvwWZ/Dz1+R4B6nC0p7LC8oyRQz/oDUueaz82DUGaGptowJuXJWnEkPuXhSfdetYWfmbjhOmBztYQzOLvAp7C0BXHkE7fDEZK4sVKnNh7HofUnjp7vk8UxwDK8kF8bW/FvgLxi/PWD7yC67BXSfR82ZKOtvKpi7C90WN207rY1ETQPQ7j7DvbqjX+EsVAnwqlVEWlnTxUy/MgVxdoxd2l8WHVVigUensA9sd/ISy9ekNYr1G5foJU5L+JFxWZETYMo5sKTQaQQ8H4NlLkJLNkYb/QKWqB+1kAs4d6stbn8l9aA+VTdB8OJ3iIMx4xUChhi1pZ8s5hcMWNmMxdRxqH+/a06kzbR4AoEDWLTHOT96Lfgi9tVShBLnWMq3JT8iy5IRxFbwNuYPvGV2Q/itp8LsINIvLvVQDWA+f48NS53t/jgwahxqlMmnhl1VaPFWgdLLdXaCzKENsqQmsDXScpoVUbEPmcwmbvsBIN5P2xI7swx+m3qryn36Z5Fnr3jKepCy24lsn85LPAggOv5wFmmL/BlfI="
  on:
    tags: true